chemtrack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name="admin"),
    path('', include('chemtrack_app.urls'), name="main"),
]

chemtrack_app/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.index, name='index'),

    path('check_template', views.check_template, name='template_check'),

    path('student_drafts/', views.student_dafts_view, name='student_drafts'),

    path('student_records/', views.student_records_view, name='student_records'),

    path('teacher_records/', views.teacher_records_view, name='teacher_records'),

    path('search_student/', views.teacher_search_student, name='search_student'),
    # Initial page to create a draft
    path('new_draft/', views.create_draft, name='new_draft'),
    # Main page, modifying drafts
    path('view_record/<int:record_id>', views.view_record, name='view_record'),

    # Backend to modify level in DB
    path('ajax/update_level', views.update_level, name='update_level'),

    path('ajax/update_statement', views.update_statement, name='update_statement')
]

chemtrack_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

class Assignment(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='assignment_as_student')
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assignment_as_teacher')

    def __str__(self):
        return f"Student: {self.student}, Teacher: {self.teacher}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cid = models.TextField(max_length=15, blank=True, default="")

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Category_template(models.Model):
    name = models.CharField(max_length=200, default="")
    description = models.TextField(default="")

    def __str__(self):
        return f"{self.pk} : {self.name}"


class Descriptor_template(models.Model):
    name = models.CharField(max_length=200, default="")
    description = models.TextField(default="")

    def __str__(self):
        return f"{self.pk} : {self.name}"


class Record(models.Model):
    date_creation = models.DateTimeField(auto_now_add=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    state = models.IntegerField(default=0)
    levels = models.IntegerField(default=0)
    name = models.CharField(max_length=100, default="")
    description = models.TextField(default="")


class Record_category(models.Model):
    template = models.ForeignKey(Category_template, on_delete=models.CASCADE)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    draft_level = models.IntegerField(default=0)
    feedback_level = models.IntegerField(default=0)
    final_level = models.IntegerField(default=0)


class Record_descriptor(models.Model):
    template = models.ForeignKey(Descriptor_template, on_delete=models.CASCADE)
    category = models.ForeignKey(Record_category, on_delete=models.CASCADE)
    draft_level = models.IntegerField(default=0)
    feedback_level = models.IntegerField(default=0)
    final_level = models.IntegerField(default=0)
    draft_statement = models.TextField(default="", blank=True)
    feedback_statement = models.TextField(default="", blank=True)
    final_statement = models.TextField(default="", blank=True)

chemtrack_app/controllers/check_template.py
#
# Function that checks whether the json template provided is valid with what
# is in the database
#       Checks that the categories exist
#       Checks that the descriptors exist
#
#
import json
from django.conf import settings
from ..models import Category_template, Descriptor_template


def check_template():
    result = True
    err = ""
    with open(settings.TEMPLATE_RECORD, "r") as file:

        data = json.load(file)

        for category in data["categories"]:

            # if the category is not in the database
            if not Category_template.objects.filter(pk=category["id"]).exists():
                result = False
                err += f"Invalid category id {category['id']} <br/>"

            # If a descriptor for this category is missing
            if not (Descriptor_template.objects.filter(pk__in=category["descriptors"]).count() == len(category["descriptors"])):
                result = False
                err += f"Invalid descriptor id in {category['descriptors']} <br/>"


    return result, err

chemtrack_app/controllers/groups.py
def is_student(user):
    return user.groups.filter(name='student').exists()

def is_teacher(user):
    return user.groups.filter(name='teacher').exists()

chemtrack_app/controllers/record.py
from ..models import Record, Record_category, Record_descriptor, Descriptor_template, Category_template
from django.utils import timezone
import json
from django.conf import settings
from .templates import get_template
from .groups import is_teacher, is_student

#   Helper function that creates new records based on the current template
#
#

def create_record(student, name, description, date):
    """

    :param student_cid: string : CID of the student
    :return: id of new record
    """
    new_record = Record(date_creation=timezone.now(), student=student, name=name, description=description, date=date)
    new_record.save()


    template = get_template()


    for category in template:
        new_category = Record_category(template=category["category"], record=new_record)
        new_category.save()

        for descriptor  in category["descriptors"]:

            new_descriptor= Record_descriptor(template=descriptor, category=new_category)
            new_descriptor.save()




    return new_record.pk

def has_acces_to(record, user):
    if is_teacher(user):
        return True
    elif is_student(user) and record.student == user:
        return True
    else:
        return False

def can_modify(record, user, state):
    """
        Function that decides if the user can modify a specific field
            Teacher can modify only feedback
            Students can modify Drafts and Final statements

        state is the state of the field of the descriptor considered:
            0:Draft
            1:FeedBack
            2:Final
    """
    if has_acces_to(record, user):
        if is_teacher(user) and state == 1 and record.state == 1:
            return True
        elif is_student(user) and state == 0 and record.state == 0:
            return True
        elif is_student(user) and state == 2 and record.state == 2:
            return True
    return False

def can_submit(record, user):
    result = False
    if record.state == 0 or record.state == 2:
        if is_student(user):
            result = True
    elif record.state == 1 or record.state == 3:
        if is_teacher(user):
            result = True
    return result

chemtrack_app/controllers/templates.py
#
# Function that checks whether the json template provided is valid with what
# is in the database
#       Checks that the categories exist
#       Checks that the descriptors exist
#
#
import json
from django.conf import settings
from ..models import Category_template, Descriptor_template


def check_template():
    result = True
    err = ""
    with open(settings.TEMPLATE_RECORD, "r") as file:

        data = json.load(file)

        for category in data["categories"]:

            # if the category is not in the database
            if not Category_template.objects.filter(pk=category["id"]).exists():
                result = False
                err += f"Invalid category id {category['id']} <br/>"

            # If a descriptor for this category is missing
            if not (Descriptor_template.objects.filter(pk__in=category["descriptors"]).count() == len(category["descriptors"])):
                result = False
                err += f"Invalid descriptor id in {category['descriptors']} <br/>"


    return result, err

def get_template():
    with open(settings.TEMPLATE_RECORD, "r") as file:

        data = json.load(file)
        result = []

        for category_id in data["categories"]:

            # if the category is not in the database
            category = Category_template.objects.filter(pk=category_id["id"])[0]

            descriptors = []
            for desc_id in category_id["descriptors"]:
                desc = Descriptor_template.objects.filter(pk=desc_id)[0]
                descriptors.append(desc)

            result.append({"category":category, "descriptors":descriptors})


    return result

chemtrack_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .controllers import check_template as controller_check_template

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def check_template(request):

    template_ok, err = controller_check_template.check_template()
    if template_ok:
        return HttpResponse("Template Valid !")
    else:
        return HttpResponse("Template not valid. <br/> Check : <br/>"+err)

chemtrack_app/views/ajax.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from .. import controllers
from ..models import Record_descriptor
from django import forms
from django.http import JsonResponse


class update_level_form(forms.Form):
    new_level = forms.IntegerField(required=True)
    descriptor = forms.CharField(required = True)
    state = forms.IntegerField(required=True)


class update_statement_form(forms.Form):
    new_text = forms.CharField()
    descriptor = forms.IntegerField(required = True)
    state = forms.IntegerField(required=True)

def check_level_values(new_level, state):
    if state == 0 or state == 2:
        if new_level >= 1 or new_level <= 6:
            return True
    elif state == 1:
        if new_level >= 1 or new_level <= 3:
            return True
    return False


def check_text_values(new_text, state):
    """
        Overkill function
        There in case in the future checks want to be made on the content of the statements
    """
    if state == 0 or state == 2:
        return True
    elif state == 1:
        return True
    return False

login_required()
def update_statement(request):
    if request.method == 'POST':
        form = update_statement_form(request.POST)
        if form.is_valid():
            print("here")
            descriptor_id = form.cleaned_data["descriptor"]
            new_text = form.cleaned_data["new_text"]
            state = form.cleaned_data["state"]
            print(state)
            descriptor = Record_descriptor.objects.filter(pk=descriptor_id)

            if len(descriptor) == 1 and check_text_values(new_text, state):
                can_modif = controllers.can_modify(descriptor[0].category.record, request.user, state)
                if can_modif:
                    if state == 0:
                       descriptor[0].draft_statement = new_text
                    elif state == 1:
                       descriptor[0].draft_statement = new_text
                    else:
                       descriptor[0].draft_statement = new_text
                    descriptor[0].save()

                    return JsonResponse({"error":False,"success":True})


    return JsonResponse({"error":"Bad query","success":False})


login_required()
def update_level(request):

    if request.method == 'POST':
        form = update_level_form(request.POST)
        if form.is_valid():
            descriptor_id = form.cleaned_data["descriptor"]
            new_level = form.cleaned_data["new_level"]
            state = form.cleaned_data["state"]

            descriptor = Record_descriptor.objects.filter(pk=descriptor_id)

            if len(descriptor) == 1 and check_level_values(new_level, state):
                can_modif = controllers.can_modify(descriptor[0].category.record, request.user, state)
                if can_modif:
                    if state == 0:
                       descriptor[0].draft_level = new_level
                    elif state == 1:
                       descriptor[0].feedback_level = new_level
                    else:
                       descriptor[0].final_level = new_level
                    descriptor[0].save()

                    return JsonResponse({"error":False,"success":True})


    return JsonResponse({"error":"Bad query","success":False})

chemtrack_app/views/check_template.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .. import controllers


login_required()
def check_template(request):

    template_ok, err = controllers.check_template()
    if template_ok:
        return HttpResponse("Template Valid !")
    else:
        return HttpResponse("Template not valid. <br/> Check : <br/>"+err)

chemtrack_app/views/index.py
from django.shortcuts import render, redirect

def index(request):
    template = 'base.html'
    context = {}
    return render(request, template, context)

chemtrack_app/views/new_draft.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from .. import controllers
from django import forms


class NewDarftForm(forms.Form):
    name = forms.CharField(required=True)
    description = forms.CharField(required = False)
    date = forms.DateField(required=True)


login_required()
@user_passes_test(controllers.is_student)
def create_draft(request):

    if request.method == 'GET':
        template = 'chemtrack_app/students/new_draft.html'
        context = {}
        return render(request, template, context)
    elif request.method == 'POST':
        form = NewDarftForm(request.POST)

        if form.is_valid():
            new_id = controllers.create_record(request.user, form.cleaned_data["name"], form.cleaned_data["description"], form.cleaned_data["date"])
            return redirect('view_record', record_id=new_id)

        else:
            return redirect('new_draft')
    else:
        return redirect('/')

chemtrack_app/views/student_dafts_view.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from .. import controllers
from ..models import Record

login_required()
@user_passes_test(controllers.is_student)
def student_dafts_view(request):

    drafts = Record.objects.filter(student=request.user, state=0)
    final_statements = Record.objects.filter(student=request.user, state=2)
    feedbacks = Record.objects.filter(student=request.user, state=1)
    confirmations = Record.objects.filter(student=request.user, state=3)


    template = 'chemtrack_app/students/see_drafts.html'
    context = {"drafts":drafts, "final_statements":final_statements, "feedbacks":feedbacks, "confirmations":confirmations}
    return render(request, template, context)

chemtrack_app/views/student_records_view.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from .. import controllers
from ..models import Record

login_required()
@user_passes_test(controllers.is_student)
def student_records_view(request):

    records = Record.objects.filter(student=request.user, state=4).order_by('-pk')


    template = 'chemtrack_app/students/see_records.html'
    context = {"records":records}
    return render(request, template, context)

chemtrack_app/views/teacher_records_view.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from .. import controllers
from ..models import Record, Assignment

login_required()
@user_passes_test(controllers.is_teacher)
def teacher_records_view(request):

    student_cids = Assignment.objects.filter(teacher=request.user).values_list('student', flat=True)

    feedback = Record.objects.filter(student__in=student_cids, state=1)
    confirmation = Record.objects.filter(student__in=student_cids, state=3)


    template = 'chemtrack_app/teachers/see_records.html'
    context = {"feedback":feedback, "confirmation":confirmation}
    return render(request, template, context)

chemtrack_app/views/view_draft.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from ..models import Record
from .. import controllers
from django import forms


login_required()
@user_passes_test(controllers.is_student)
def view_draft(request, draft_id=-1):
    # If no id are in the url
    if draft_id == -1:
        if controllers.is_student(request.user):
            return redirect('student_drafts')
        else:
            return redirect('/')
    else:
        template = 'record_management/draft.html'

        draft=  Record.objects.filter(pk=draft_id)

        context = {"record":draft}
        return render(request, template, context)

chemtrack_app/templates/chemtrack_app/record_management/record.html
{% extends "../../base.html" %}
{% load record %}
{% load groups %}

{% block content %}
    <center><h1 id="draft_name">{{record.name}}</h1></center>
    <p id="draft_description" >
        Description: {{record.description}} <br>
        Date: {{record.date}} <br>
        Created the: {{record.date_creation}} <br>
        Student: {{record.student}}, {{record.student.profile.cid}} <br>
        State:
            {% if record.state is 0 %}
                Draft Stage
            {% elif record.state is 1 %}
                Waiting for feedback by teachers
            {% elif record.state is 2 %}
                Waiting for final submission by student
            {% elif record.state is 3%}
                Waiting for final confirmation by teachers
            {% else %}
                Final record
            {% endif %}
    </p>

    <div id="side_menu">
        {% for category in record.record_category_set.all%}
            <div class="cat_menu_element
                {# Selects by default the first category #}
                {% if forloop.counter0 == 0%}
                    selected
                {% endif %}"
                    id="category_menu_{{forloop.counter0}}">
                {{category.template.name}}
            </div>
        {% endfor %}

        <div class="cat_menu_element">
            <center><a href="{% url 'view_record' record.pk %}?page=admin" class="no_style_link">Admin</a></center>
        </div>

        {% can_submit record user as can_submit_flag %}

        {% if can_submit_flag %}
            <div class="cat_menu_element">
                <center>
                    <form href="{% url 'view_record' record.pk %}" method="POST">

                        {% csrf_token %}
                        <input type="submit" value="submit" name="submit_record" onclick="return confirm('Please confirm that you are submitting')"/>
                    </form>
                </center>
            </div>
        {% endif %}




    </div>
    <div id="record_area">


        {% for category in record.record_category_set.all %}
            <div class="category_container {% if forloop.counter0 == 0 %} selected {%endif%}"
                 id="category_container_{{forloop.counter0}}">

                <script>

                $("#category_menu_{{forloop.counter0}}").click(function () {
                    $(".cat_menu_element").removeClass("selected");
                    $(".category_container").removeClass("selected");
                    $("#category_menu_{{forloop.counter0}}").addClass("selected");
                    $("#category_container_{{forloop.counter0}}").addClass("selected");
                });
                </script>



                <div id="category_{{forloop.counter0}}">
                    <div class="tooltip"><h3 class="category_title">{{category.template.name}}</h3>
                      <span class="tooltiptext">{{category.template.description}}</span>
                    </div>
                </div>
                {% for descriptor in category.record_descriptor_set.all %}

                <div class="tooltip">
                    <h4>{{descriptor.template.name}}</h4>
                      <span class="tooltiptext">{{descriptor.template.description}}</span>
                </div>

                    <div class="descriptor_state_choice">
                        <div id="choice_{{forloop.parentloop.counter0}}_{{forloop.counter0}}_0"
                             class="descriptor_display_choice {% pre_select record 0%}">Draft</div>
                        <div id="choice_{{forloop.parentloop.counter0}}_{{forloop.counter0}}_1"
                             class="descriptor_display_choice {% pre_select record 1%}">Feedback</div>
                        <div id="choice_{{forloop.parentloop.counter0}}_{{forloop.counter0}}_2"
                             class="descriptor_display_choice {% pre_select record 2%}">Final</div>
                    </div>

                    {# Looping through the 3 states of the draft #}

                    {% with 'Draft Feedback Final' as list %}
                        {% for i in list.split %}

                            {# Scripts for toggling the descriptors stages #}
                            <script>

                                $("#choice_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}").click(function () {
                                    $("#choice_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}").toggleClass("selected");
                                    $("#descriptor_container_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}").toggleClass("selected");
                                });
                            </script>

                            {# Compute if the user can modify this part of the descriptor #}
                            {% can_modify record user forloop.counter0 as can_modify_flag %}

                            <div
                                    id="descriptor_container_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}"
                                    class="descriptor_container {% pre_select record forloop.counter0%}"
                            >

                                <h6>{{i}}</h6>

                                {% list_levels_generate forloop.counter0 as list_levels %}
                                    <div
                                            id="level_containers_{{forloop.parentloop.parentloop.counter0}}_{{forloop.counter0}}"
                                            class="level_container"
                                    >
                                        {% for j in list_levels %}

                                            <div
                                                    id="level_{{forloop.parentloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter}}"
                                                    class="level_button {%is_descriptor_selected descriptor forloop.parentloop.counter0 forloop.counter%} {% if can_modify_flag is False %} notclickable {% endif %}"
                                            >
                                                {{j}}
                                            </div>

                                            {% if can_modify_flag %}
                                                <script>
                                                    var token = '{{csrf_token}}';

                                                    $("#level_{{forloop.parentloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter}}").click(function (event) {
                                                            $.ajax({
                                                              type: "POST",
                                                              headers: { "X-CSRFToken": token },
                                                              url: "{% url "update_level" %}",
                                                              dataType: "json",
                                                              data: {
                                                                'new_level': {{forloop.counter}},
                                                                'descriptor': {{descriptor.pk}},
                                                                'state': {{forloop.parentloop.counter0}},
                                                              },
                                                              success: function (data) {
                                                              console.log(data);
                                                                var returnedData =data;
                                                                if (returnedData["success"]) {
                                                                    $("[id^=level_{{forloop.parentloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}]").removeClass("selected")
                                                                    $("#level_{{forloop.parentloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter}}").addClass("selected")
                                                                } else {
                                                                    alert("there was an error, refresh using Ctrl+F5");
                                                                }
                                                              },
                                                              error: function () {
                                                                alert("there was an error, refresh using Ctrl+F5")
                                                              }
                                                            });
                                                            return false;
                                                    });

                                                </script>
                                            {% endif %}
                                        {% endfor %}
                                    </div>

                                <br>

                                <textarea
                                        id="statement_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}"
                                        class="descriptor_text" {% if can_modify_flag is False %} disabled {% endif %}
                                >{%if forloop.counter0 is 0 %}{{descriptor.draft_statement}}{%elif forloop.counter0 is 1%}{{descriptor.feedback_statement}}{%else%}{{descriptor.final_statement}}{%endif%}</textarea>
                                {% if can_modify_flag %}
                                    <script>
                                        var token = '{{csrf_token}}';
                                        $("#statement_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}").keyup(function (event) {
                                            $.ajax({
                                              type: "POST",
                                              headers: { "X-CSRFToken": token },
                                              url: "{% url "update_statement" %}",
                                              dataType: "json",
                                              data: {
                                                'new_text': $("#statement_{{forloop.parentloop.parentloop.counter0}}_{{forloop.parentloop.counter0}}_{{forloop.counter0}}").val(),
                                                'descriptor': {{descriptor.pk}},
                                                'state': {{forloop.counter0}},
                                              },
                                              success: function (data) {
                                              console.log(data);
                                                var returnedData =data;
                                                if (returnedData["success"]) {
                                                    console.log("update successful")
                                                } else {
                                                    alert("there was an error, refresh using Ctrl+F5");
                                                }
                                              },
                                              error: function () {
                                                alert("there was an error, refresh using Ctrl+F5")
                                              }
                                            });
                                            return false;
                                        });

                                    </script>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% endwith %}

                    <hr>
                {% endfor %}

            </div>
        {% endfor %}


    </div>
{% endblock %}